version: 0.2

env:
  variables:
    repository: "https://github.com/hannesortmeier/dicer.git"
  parameter-store:
    email: "E-Mail"

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - echo 'updating...'
      - npm update
      - echo 'installing dependencies...'
      - npm install
  build:
    commands:
      - echo 'building...'
      - npm run build
      - gzip -r dist
      
artifacts:
  files:
    - 'dist.zip'
  name: dicer.pro-$(date +%Y-%m-%d).zip